version: "3.3"

services:
    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: production
        ports:
            - "3306:3306"
    db-test:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: staging
        ports:
            - "3307:3306"
